// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrpyukrdkajotbjlaacg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFycHl1a3Jka2Fqb3RiamxhYWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjI1ODIsImV4cCI6MjA2NDkzODU4Mn0.6-S_RUex_XLqjthzT3O2jRy7hHmzPzrTY4LiVInIoig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);